// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKnE6t4BxCJfk0l9hUmLO5pGtzoNDgecI',
    appId: '1:270287599696:android:7a78d1ff603a92b5933955',
    messagingSenderId: '270287599696',
    projectId: 'skdev-302ae',
    databaseURL: 'https://skdev-302ae-default-rtdb.firebaseio.com',
    storageBucket: 'skdev-302ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE3Ea4lBDw2H05aIhYpmL1GvxpoNcIJRY',
    appId: '1:270287599696:ios:31d7a2450248bb4e933955',
    messagingSenderId: '270287599696',
    projectId: 'skdev-302ae',
    databaseURL: 'https://skdev-302ae-default-rtdb.firebaseio.com',
    storageBucket: 'skdev-302ae.appspot.com',
    androidClientId: '270287599696-eqrlb5uohagrc183om5ph42thi4hsnq3.apps.googleusercontent.com',
    iosBundleId: 'com.app.photocrew',
  );
}
